# fly.toml app configuration file generated for linkai-tika-service on 2025-06-26T11:58:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linkai-tika-service'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = 30

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 9998
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  JAVA_OPTS = "-Xmx1g -server"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
