# fly.toml app configuration file generated for voice-server on 2025-06-04T18:36:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "voice-server"
primary_region = "mia"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 800
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = 5000
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

[metrics]
  port = 9091
  path = "/metrics"
